version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CGO_ENABLED=0
      - DOCKER_BUILDKIT=1
    develop:
      watch:
        - path: .
          action: rebuild
    volumes:
      - ./database:/app/database/